<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit552f550ab5dcf65a4e37923b56321247
{
    public static $prefixLengthsPsr4 = array (
        'v' => 
        array (
            'voku\\' => 5,
        ),
        'S' => 
        array (
            'StopWords\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'voku\\' => 
        array (
            0 => __DIR__ . '/..' . '/voku/stop-words/src/voku',
        ),
        'StopWords\\' => 
        array (
            0 => __DIR__ . '/..' . '/juanantoniodelgado/stopwords/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Text' => 
            array (
                0 => __DIR__ . '/..' . '/pear/text_languagedetect',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit552f550ab5dcf65a4e37923b56321247::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit552f550ab5dcf65a4e37923b56321247::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit552f550ab5dcf65a4e37923b56321247::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit552f550ab5dcf65a4e37923b56321247::$classMap;

        }, null, ClassLoader::class);
    }
}
