<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '1bad861b825bfd22350781c4d6ed527b7d4a83d6',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '1bad861b825bfd22350781c4d6ed527b7d4a83d6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'juanantoniodelgado/stopwords' => array(
            'pretty_version' => '1.3',
            'version' => '1.3.0.0',
            'reference' => '90128e417f03dcc8d5b32ad8b91f063bc309176f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../juanantoniodelgado/stopwords',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/text_languagedetect' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '655b269959782416426cf0aa7bd47e19fed63210',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/text_languagedetect',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/stop-words' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '8e63c0af20f800b1600783764e0ce19e53969f71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/stop-words',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
